# Generated by Django 4.1.4 on 2022-12-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=55)),
                ('logo', models.ImageField(upload_to='media/computer/images')),
            ],
        ),
    ]
