# Generated by Django 4.1.4 on 2022-12-20 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_rename_computerbrands_computerbrand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='total_price',
        ),
    ]
