# Generated by Django 4.1.4 on 2022-12-20 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0003_remove_computer_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computerinfo', to='computer.computerspecification'),
        ),
    ]
